# SPDX-License-Identifier: GPL-2.0
#
# Makefile for the drm device driver.  This driver provides support for the
# Direct Rendering Infrastructure (DRI) in XFree86 4.1.0 and higher.

gray-gpu-y := gray_drv.o

obj-$(CONFIG_GRAY_GPU) += gray-gpu.o
